version: "2"

# all available settings of specific linters
linters-settings:
  govet:
    # settings per analyzer
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gosec:
    settings:
      exclude: "G401"
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  include:
    - EXC01
    - EXC02

linters:
  # enable or disable analyzers by name
  enable:
    - gofmt
    - gosec
    - whitespace
    - misspell
    - unconvert
    - goimports
    - unused
    - gosimple
    - govet
    - staticcheck
  disable-all: true
